### ISSUE TITLE
Why OriginProtocolPolicy = http-only?

### ISSUE THREAD

**Issue by jgarber** [donaldpiret/asset_hash#1]
Why do you use http-only for OriginProtocolPolicy. Shouldn't Amazon CloudFront get files from the origin server using the same protocol as was requested? Is there a reason you didn't choose match-viewer?

**Comment by jgarber** [comment]
I created a new distribution with Match Viewer as the Protocol Policy and it solved my problem (an Apache rewrite rule wasn't being applied on the basis of HTTPS). I recommend you use match-viewer in the rake task, but perhaps you have reasons not to?

**Comment by agibralter** [comment]
+1 That's what I did when I made it manually.

**Comment by donaldpiret** [comment]
I'll set this as an option in the raketask in the next release, thanks for the feedback guys

**Comment by donaldpiret** [comment]
Resolved in 0.2.1 by allowing you to select the protocol policy during the rake task
