### ISSUE TITLE
Show instructions at the end of the rake task

### ISSUE THREAD

**Issue by jgarber** [donaldpiret/asset_hash#2]
I used the rake task to create a custom origin CloudFront distribution. At the end, I was given the ID of the distribution, but I mistakenly thought that was what I should use as part of the domain. Instead, it would be nice to report the domain name of the distribution to the user. Even better, output the lines that the user should paste in their environment file with the domain name filled in!

**Comment by agibralter** [comment]
Also +1. I was confused by the reference to Distribution ID in the documentation as the cloudfront.net subdomain.

**Comment by donaldpiret** [comment]
Resolved in 0.2.1 by having better instructions during the task, thank for the feedback guys!
