### ISSUE TITLE
caching fingerprints

### ISSUE THREAD

**Issue by agibralter** [donaldpiret/asset_hash#4]
In the README you have an example asset_path proc:

``` ruby
config.action_controller.asset_path = Proc.new do |source|
  AssetHash.fingerprint(source)
end
```

Ideally, this proc should not touch the filesystem for every asset of every request. I have an example of what I'm using, though it's written for Rails 2.3.11 and has to monkey patch `ActionView::Helpers::AssetTagHelper`.

``` ruby
module AssetFingerprints

  @@cache = {}
  @@cache_guard = Mutex.new

  def self.included(base)
    base.class_eval do
      alias_method_chain :rewrite_asset_path, :fingerprints
    end
  end

  def rewrite_asset_path_with_fingerprints(source)
    if !@@cache[source]
      @@cache_guard.synchronize do
        @@cache[source] = AssetHash.fingerprint(source)
      end
    end
    @@cache[source]
  end
end

ActionView::Helpers::AssetTagHelper.class_eval do
  include AssetFingerprints
end
```

But that's the basic idea. What about including the `proc` in the asset_hash gem?

Then people could do:

``` ruby
config.action_controller.asset_path = AssetHash.fingerprinter
```

**Comment by bhellman1** [comment]
Does rails have to hit the file system anyways to see if the file is there?

**Comment by agibralter** [comment]
Yeah, the first time, but ideally not on every request, right?

**Comment by bhellman1** [comment]
Is there a way to confirm that? It would be nice to see the before and after. 

Also, to try your solution, how/where do you install that module? Thanks

**Comment by agibralter** [comment]
Well looking at this code: https://github.com/donaldpiret/asset_hash/blob/master/lib/asset_hash.rb#L56-66

It looks like

``` ruby
config.action_controller.asset_path = Proc.new do |source|
  AssetHash.fingerprint(source)
end
```

will call `Digest::MD5.file(path).hexdigest` every time an asset path is required (e.g. `image_tag`).

Here is a gist of how I've integrated the module into my app: https://gist.github.com/1169463

I'm not sure the best way to reconcile all this into one gem. I think that Rails 3.1 is going in the direction of asset hashes by default...
