### ISSUE TITLE
Assets keep getting re-hashed?

### ISSUE THREAD

**Issue by bhellman1** [donaldpiret/asset_hash#5]
Seems like the hashing hashes an existing hash no?

images/embed/icons/social/facebook_16.png
images/embed/icons/social/facebook_16_2-086ea8a406fdde652ced4e45d3333c85.gif
images/embed/icons/social/facebook_16_2-086ea8a406fdde652ced4e45d3333c85-086ea8a406fdde652ced4e45d3333c85.gif

Would it be good to remove an old hash when a new hash is created?

**Comment by donaldpiret** [comment]
Hi,

The hashing functionality is meant to be run once after deployment of your app only, running it multiple times on the same deploy directory will indeed produce duplicate hashes. 
It might be a good idea to ignore or delete already hashed files though, i'll try to implement that for the next version.
